---
services: docker

env:
  - distro: debian8
  - distro: debian9
  - distro: ubuntu1604
  - distro: ubuntu1804

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export postgresql_bin_dir=/usr/lib/postgresql/9.6/bin
  - export postgresql_data_dir=/var/lib/postgresql/9.6/main

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Check PostgreSQL status.
  - 'docker exec -u postgres ${container_id} ${postgresql_bin_dir}/pg_ctl -D ${postgresql_data_dir} status'

after_failure:
  # Check what happened on systemd systems.
  - 'docker exec --tty ${container_id} env TERM=xterm systemctl -l status postgresql.service'
  - 'docker exec --tty ${container_id} env TERM=xterm journalctl -xe --no-pager'
  - 'docker exec --tty ${container_id} env TERM=xterm cat /etc/postgresql/9.6/main/postgresql.conf'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
