---
- name: Ensure PostgreSQL databases are present.
  become_user: postgres
  become: yes
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
    state: present
  loop: "{{ postgresql_databases }}"
