- include: setup.yml
  tags: postgresql

- include: users.yml
  tags: postgresql

- include: databases.yml
  tags: postgresql

- include: barman.yml
  tags: postgresql,barman
  when: postgresql_with_barman
