- include_tasks: setup.yml
  tags: postgresql

- include_tasks: locales.yml
  tags: postgresql

- include_tasks: users.yml
  tags: postgresql

- include_tasks: databases.yml
  tags: postgresql

- name: Include barman tasks
  include_tasks: barman.yml
  tags: postgresql,barman
  when: postgresql_with_barman

- name: Include zabbix tasks
  include_tasks: zabbix.yml
  tags: zabbix,zabbix-agent
