- include_tasks: setup.yml
  tags: postgresql

- include_tasks: users.yml
  tags: postgresql

- include_tasks: databases.yml
  tags: postgresql

- include_tasks: barman.yml
  tags: postgresql,barman
  when: postgresql_with_barman
