
- name: Be sure pgBadger packages are installed
  apt:
    name: '{{ postgresql_pgbadger_packages }}'
    state: present

- name: Be sure pgBadger output directory exists
  file:
    path: '{{ postgresql_pgbadger_output_dir }}'
    state: directory
    recurse: yes
    mode: 0755

- name: Update pgBadger user access
  htpasswd:
    path: /etc/nginx/.htpasswd_pgbadger
    name: '{{ postgresql_pgbadger_user }}'
    password: '{{ postgresql_pgbadger_password }}'
    owner: root
    group: "{{ nginx_group | default('www-data') }}"
    mode: 0640

- name: Provide pgBadger nginx configuration
  tags: nginx
  template:
    src: nginx/pgbadger.j2
    dest: /etc/nginx/pgbadger.conf
  notify: reload nginx
