
- name: Be sure PostGIS packages are installed
  apt:
    name: '{{ item }}'
    state: "{{ apt_state | default('present') }}"
    update_cache: "{{ apt_update_cache | default('yes') }}"
    cache_valid_time: '{{ apt_cache_valid_time | default(600) }}'
  with_items: '{{ postgresql_postgis_packages }}'
