- name: Be sure PostgreSQL are installed
  apt:
    name: '{{ item }}'
    state: "{{ apt_state | default('present') }}"
    update_cache: "{{ apt_update_cache | default('yes') }}"
    cache_valid_time: '{{ apt_cache_valid_time | default(600) }}'
  with_items: '{{ postgresql_packages }}'

- include: postgis.yml
  when: postgresql_with_postgis

- include: pgbadger.yml
  when: postgresql_with_pgbadger

- include: cleanup_pgbadger.yml
  when: not postgresql_with_pgbadger
  
- name: Ensure PostgreSQL is started and enabled to start at boot.
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Install PostgreSQL zabbix configuration
  tags: zabbix-agent
  copy:
    src: userparameter_pgsql.conf
    dest: /etc/zabbix/zabbix_agentd.{{ 'd' if zabbix_use_repo is defined and zabbix_use_repo else 'conf.d' }}/userparameter_pgsql.conf
  notify: restart zabbix-agent
  when: postgresql_with_zabbix_monitoring

- name: Update PostgreSQL configuration
  template:
    src: '{{ postgresql_version }}/main/postgresql.j2'
    dest: '/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf'
  notify: restart postgresql

- name: Update PostgreSQL hba configuration
  template:
    src: pg_hba.j2
    dest: '/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf'
  notify: restart postgresql
