- stat: path=/etc/zabbix
  register: zabbix_config_exists

- name: Zabbix monitoring
  block:
    - name: Set zabbix configuration directory
      set_fact: zabbix_agentd_dir=/etc/zabbix/zabbix_agentd.{{ 'd' if zabbix_use_repo is defined and zabbix_use_repo else 'conf.d' }}

    - name: Install PostgreSQL zabbix configuration
      template:
        src: zabbix/userparameter_pgsql.conf.j2
        dest: '{{ zabbix_agentd_dir }}/userparameter_pgsql.conf'
      notify: restart zabbix-agent
      when: zabbix_monitoring and (zabbix_agent_remove is undefined or not zabbix_agent_remove)

    - name: Remove zabbix configuration
      file:
        path: '{{ zabbix_agentd_dir }}/userparameter_pgsql.conf'
        state: absent
      notify: restart zabbix-agent
      when: not zabbix_monitoring

  when: zabbix_config_exists.stat.exists

- name: Add zabbix PostgreSQL 9.6 user
  become_user: postgres
  become: yes
  postgresql_user:
    name: '{{ postgresql_zabbix_user }}'
    password: '{{ postgresql_zabbix_password }}'
    priv: 'pg_stat_database:SELECT'
    state: present
  no_log: true
  when: postgresql_version == '9.6'

- name: Add zabbix PostgreSQL user
  become_user: postgres
  become: yes
  postgresql_user:
    name: '{{ postgresql_zabbix_user }}'
    password: '{{ postgresql_zabbix_password }}'
    role_attr_flags: pg_monitor
    state: present
  when: postgresql_version != '9.6'

- name: Install zabbix sql PostgreSQL files
  synchronize:
    src: zabbix/postgresql
    dest: '{{ zabbix_agent_home }}'
  when: zabbix_monitoring

- name: Remove zabbix PostgreSQL user
  become_user: postgres
  become: yes
  postgresql_user:
    name: '{{ postgresql_zabbix_user }}'
    state: absent
  when: not zabbix_monitoring

- name: Remove zabbix sql postgresql files
  file:
    path: '{{ zabbix_agent_home }}/postgresql'
    state: absent
  when: not zabbix_monitoring
