- stat: path=/etc/zabbix
  register: zabbix_config_exists

- name: Add zabbix PostgreSQL 9.6 user
  become_user: postgres
  become: yes
  postgresql_user:
    name: '{{ postgresql_zabbix_user }}'
    password: '{{ postgresql_zabbix_password }}'
    state: present
  no_log: yes
  when: zabbix_monitoring and postgresql_version == '9.6'

- name: Set zabbix PostgreSQL 9.6 grant
  become_user: postgres
  become: yes
  command: psql postgres -c 'GRANT SELECT ON pg_stat_database TO {{ postgresql_zabbix_user }};'
  when: zabbix_monitoring and postgresql_version == '9.6'

- name: Add zabbix PostgreSQL user
  become_user: postgres
  become: yes
  postgresql_user:
    name: '{{ postgresql_zabbix_user }}'
    password: '{{ postgresql_zabbix_password }}'
    state: present
  no_log: yes
  when: zabbix_monitoring and postgresql_version != '9.6'

- name: Set zabbix PostgreSQL grant
  become_user: postgres
  become: yes
  command: psql postgres -c 'GRANT pg_monitor TO {{ postgresql_zabbix_user }};'
  when: zabbix_monitoring and postgresql_version != '9.6'

- name: Install zabbix sql PostgreSQL files
  synchronize:
    src: zabbix/postgresql
    dest: '{{ zabbix_agent_home }}'
    group: no
    owner: no
  when: zabbix_monitoring

# @TODO: this does not work with synchronize at the moment
- name: Set owner for sql PostgreSQL files
  file:
    path: '{{ zabbix_agent_home }}/postgresql'
    state: directory
    recurse: yes
    owner: zabbix
    group: zabbix
  when: zabbix_monitoring

- name: Remove zabbix PostgreSQL user
  become_user: postgres
  become: yes
  postgresql_user:
    name: '{{ postgresql_zabbix_user }}'
    state: absent
  when: not zabbix_monitoring

- name: Remove zabbix sql postgresql files
  file:
    path: '{{ zabbix_agent_home }}/postgresql'
    state: absent
  when: not zabbix_monitoring
